# Generated by Django 4.0.5 on 2022-09-24 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_auditor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del auditor')),
                ('cargo_auditor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del auditor')),
                ('area_auditor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area a auditar')),
                ('informe_auditor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Informe del auditor')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
            },
        ),
        migrations.CreateModel(
            name='auditoria1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_auditorias', models.CharField(max_length=150, verbose_name='Cedula')),
                ('image', models.ImageField(default='null', upload_to='users', verbose_name='Imagen')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('tipoDocumento', models.ManyToManyField(blank=True, to='auditoria.auditoria', verbose_name='Tipo de documento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'auditoria1',
                'verbose_name_plural': 'auditorias1',
            },
        ),
    ]
