# Generated by Django 4.1.1 on 2022-09-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pagomatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('Apellido', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido')),
                ('Cedula', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cedula')),
                ('carrera', models.CharField(blank=True, max_length=150, null=True, verbose_name='Carrera')),
                ('Semestre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Semestre')),
                ('valorsemestre', models.CharField(blank=True, max_length=150, null=True, verbose_name='valorsmestre')),
                ('saldopendiente', models.CharField(blank=True, max_length=150, null=True, verbose_name='saldopendiente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=150, verbose_name='Cedula')),
                ('Nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('Apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('Carrera', models.CharField(max_length=150, verbose_name='Carrera')),
                ('Semestre', models.CharField(max_length=150, verbose_name='Semestre')),
                ('Valorsemestre', models.CharField(max_length=150, verbose_name='Valorsemestre')),
                ('Saldopendiente', models.CharField(max_length=150, verbose_name='Saldopendiente')),
                ('fmatricula', models.DateField(blank=True, null=True, verbose_name='Fecha de Matricula')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('tipoDocumentos', models.ManyToManyField(blank=True, to='pagomatricula.pagomatricula', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
    ]
