# Generated by Django 4.1.1 on 2022-09-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admitidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitir',
            name='pasoalsemestre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Semestre Pasado'),
        ),
    ]
