# Generated by Django 4.1.1 on 2022-09-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admitidos', '0002_alter_admitir_pasoalsemestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitir',
            name='apellidos',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='admitir',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres'),
        ),
    ]
