# Generated by Django 4.1.1 on 2022-09-23 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres del Estudiante')),
                ('Apellido', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos del Estudiante')),
                ('cedula', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cedula')),
                ('celular', models.CharField(blank=True, max_length=100, null=True, verbose_name='Celular')),
                ('carrera', models.CharField(blank=True, max_length=100, null=True, verbose_name='Carrera')),
                ('facultad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantess',
            },
        ),
        migrations.CreateModel(
            name='Estudiantess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horasdesalida', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hora de Salida')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('tipoDocumento', models.ManyToManyField(blank=True, to='estudiante.estudiante', verbose_name='Estudiantes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estudiantess',
                'verbose_name_plural': 'Estudiante',
            },
        ),
    ]
