# Generated by Django 4.1.1 on 2022-09-23 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('identificacionprofe', models.CharField(blank=True, max_length=150, null=True, verbose_name='Numero de Identificacion del Profesor')),
                ('carrera', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion')),
                ('asignatura', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoContrato', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de Contrato')),
                ('tecnico', models.BooleanField(verbose_name='Si/No')),
                ('tecnicoen', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tecnico en: ')),
                ('tecnologo', models.BooleanField(verbose_name='Si/No')),
                ('tecnologoen', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tecnologo en: ')),
                ('profesional', models.BooleanField(verbose_name='Si/No')),
                ('profesionalen', models.CharField(blank=True, max_length=150, null=True, verbose_name='Profesional en: ')),
                ('posgrado', models.BooleanField(verbose_name='¿Tiene algun doctorado, maestria, o otro tipo de especialidad? Si/No')),
                ('posgradoen', models.CharField(blank=True, max_length=150, null=True, verbose_name='Doctorado, Maestria o otro tipo de especialidad, escriba aqui...')),
                ('image', models.ImageField(default='null', upload_to='users', verbose_name='Imagen')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('tipoDocumento', models.ManyToManyField(blank=True, to='docente.docente', verbose_name='Tipo de documento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
