# Generated by Django 4.1.1 on 2022-09-23 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreprofesor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Profesor')),
                ('materia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Materia')),
                ('numerohoras', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de Horas')),
                ('diaclases', models.CharField(blank=True, max_length=100, null=True, verbose_name='Día de clases')),
            ],
            options={
                'verbose_name': 'HorariodeClase',
                'verbose_name_plural': 'Horarios de Clases',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='null', upload_to='users', verbose_name='Imagen')),
                ('pagosporhora', models.CharField(blank=True, max_length=150, null=True, verbose_name='Materia')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('tipoDocumento', models.ManyToManyField(blank=True, to='horario.horarioclase', verbose_name='Horarios de Clase')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
    ]
