# Generated by Django 4.1 on 2022-08-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='descripcio2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcions'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion'),
        ),
    ]
