# Generated by Django 4.1 on 2022-08-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_remove_tipodocumento_descripcio2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Editado'),
        ),
    ]
