# Generated by Django 4.1 on 2022-08-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_alter_tipodocumento_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumento',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='update_at',
        ),
    ]
